/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendorSettingsRouteImport } from './routes/vendor.settings'
import { Route as VendorReviewsRouteImport } from './routes/vendor.reviews'
import { Route as VendorProductsRouteImport } from './routes/vendor.products'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorHelpRouteImport } from './routes/vendor.help'
import { Route as VendorEarningsRouteImport } from './routes/vendor.earnings'
import { Route as ShopProductIdRouteImport } from './routes/shop.$productId'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'

const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendorSettingsRoute = VendorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => VendorRoute,
} as any)
const VendorReviewsRoute = VendorReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProductsRoute = VendorProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => VendorRoute,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => VendorRoute,
} as any)
const VendorHelpRoute = VendorHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => VendorRoute,
} as any)
const VendorEarningsRoute = VendorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => VendorRoute,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ShopRoute,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRouteWithChildren
  '/vendor': typeof VendorRouteWithChildren
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/help': typeof VendorHelpRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/reviews': typeof VendorReviewsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/vendor/': typeof VendorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRouteWithChildren
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/help': typeof VendorHelpRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/reviews': typeof VendorReviewsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/vendor': typeof VendorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRouteWithChildren
  '/vendor': typeof VendorRouteWithChildren
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/help': typeof VendorHelpRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/reviews': typeof VendorReviewsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/vendor/': typeof VendorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/vendor'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/vendors'
    | '/shop/$productId'
    | '/vendor/earnings'
    | '/vendor/help'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/reviews'
    | '/vendor/settings'
    | '/admin/'
    | '/vendor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/vendors'
    | '/shop/$productId'
    | '/vendor/earnings'
    | '/vendor/help'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/reviews'
    | '/vendor/settings'
    | '/admin'
    | '/vendor'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/vendor'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/vendors'
    | '/shop/$productId'
    | '/vendor/earnings'
    | '/vendor/help'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/reviews'
    | '/vendor/settings'
    | '/admin/'
    | '/vendor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ShopRoute: typeof ShopRouteWithChildren
  VendorRoute: typeof VendorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/settings': {
      id: '/vendor/settings'
      path: '/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof VendorSettingsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/reviews': {
      id: '/vendor/reviews'
      path: '/reviews'
      fullPath: '/vendor/reviews'
      preLoaderRoute: typeof VendorReviewsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/products': {
      id: '/vendor/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorProductsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/help': {
      id: '/vendor/help'
      path: '/help'
      fullPath: '/vendor/help'
      preLoaderRoute: typeof VendorHelpRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/earnings': {
      id: '/vendor/earnings'
      path: '/earnings'
      fullPath: '/vendor/earnings'
      preLoaderRoute: typeof VendorEarningsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ShopRouteChildren {
  ShopProductIdRoute: typeof ShopProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductIdRoute: ShopProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface VendorRouteChildren {
  VendorEarningsRoute: typeof VendorEarningsRoute
  VendorHelpRoute: typeof VendorHelpRoute
  VendorOrdersRoute: typeof VendorOrdersRoute
  VendorProductsRoute: typeof VendorProductsRoute
  VendorReviewsRoute: typeof VendorReviewsRoute
  VendorSettingsRoute: typeof VendorSettingsRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorEarningsRoute: VendorEarningsRoute,
  VendorHelpRoute: VendorHelpRoute,
  VendorOrdersRoute: VendorOrdersRoute,
  VendorProductsRoute: VendorProductsRoute,
  VendorReviewsRoute: VendorReviewsRoute,
  VendorSettingsRoute: VendorSettingsRoute,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ShopRoute: ShopRouteWithChildren,
  VendorRoute: VendorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
